apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: lb-clear-architecture-angular
  name: clear-architecture-angular-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: clear-architecture-angular-loadbalancer
      port: 80
      protocol: TCP
  selector:
      app: clear-architecture-angular